# Generated by Django 3.1.7 on 2021-03-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0002_auto_20210310_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='last_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
