# Generated by Django 3.1.7 on 2021-03-10 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='lastReviewAt',
            new_name='last_review_at',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='nextReviewAt',
            new_name='next_review_at',
        ),
    ]
