# Generated by Django 3.1.7 on 2021-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20210310_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='last_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='next_review_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
